# Generated by Django 3.2.5 on 2021-07-19 18:11

from django.db import migrations

NESTED_COMMENTS_SP = """
create or replace function select_comments_for_object_content(opk integer, ctype text)
  returns table (
    id integer,
    depth integer) as $$
  with recursive cte (id, path, parent_id, depth)  as (
      select id,
          array[id] as path,
          parent_id,
          1 as depth
      from comments_comment
      where parent_id is null and object_pk = opk and content_type = ctype
      union all
      select comments_comment.id,
          cte.path || comments_comment.id,
          comments_comment.parent_id,
          cte.depth + 1 as depth
      from comments_comment
      join cte on comments_comment.parent_id = cte.id
      where comments_comment.object_pk = opk and comments_comment.content_type = ctype
    )
    select id, depth from cte order by path;
$$ language sql;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [migrations.RunSQL(NESTED_COMMENTS_SP)]
